### PR TITLE
Bug fixes

### LINKED ISSUE #1: Fixing syntax errors throughout the project
## Description:
There are a lot of errors in the project which halt the program from running. (Both syntax and missing code, might be due to incorrect merging of the previous PR's)

I am interested in solving this issue.
Kindly assign it to me, @RitwikSingh28

### PR DESCRIPTION
**Pull request by AnshumaliSuri**
- Info about the issue : This PR will fix critical issues in the app which were obstructing proper functioning of the application.
- Name : Anshumali Suri
- GitHub ID : @AnshumaliSuri

Resolves #1 

## Screenshots
Screenshot 2023-10-05 at 9 00 31 AM

Screenshot_1696476678

### CODE REVIEW

File: lib/individual/user_chats_menu.dart [hunk 1]
```diff
@@ -3,7 +3,7 @@ import 'package:cura/shared/widgets/navigation-bar.dart';
 import 'package:flutter/material.dart';
 import 'package:cura/individual/home_page_individual.dart';
 import 'package:flutter_screenutil/flutter_screenutil.dart';
-import '../shared/widgets/gradient_background.dart';
+import '../shared/widgets/gradient_background.dart' as shared;
```
Comment (RitwikSingh28) [inline lib/individual/user_chats_menu.dart]: Since `UniDirectionalGradient()` is present only in one location now due to your changes, i.e. in `shared`, kindly remove the `as shared` construct, as this leads to unintentional verbosity.

**Review by RitwikSingh28 — CHANGES_REQUESTED** [review]
@AnshumaliSuri 
Kindly go through and make the changes before we can merge your work into `main` branch

File: lib/individual/user_chats_menu.dart (hunk 1 above)
Comment (AnshumaliSuri) [reply lib/individual/user_chats_menu.dart]: @RitwikSingh28 
Fixed in commit e0b6cc4

**Review by RitwikSingh28 — APPROVED** [review]
Splendid work @AnshumaliSuri 🎉

Merging into main..
